### ISSUE TITLE
Add Realistic Clouds

### ISSUE THREAD

**Issue by MrAgentBlaze** [depressed-pho/natural-mystic-shaders#17]
Like the clouds are in most shaders

**Comment by depressed-pho** [comment]
Done. I will release a new version in a few days.
Note that clouds will start to stutter after 10 minutes or so. This is due to a vanilla issue and is inevitable. The uniform TIME isn’t wrapped so it’ll start to lose precision.

![c6d3dd67-170b-4b3f-8614-47926e92d695](https://user-images.githubusercontent.com/438860/50401096-3f1cfd80-07cf-11e9-8497-7b4bcea92383.jpeg)
