### ISSUE TITLE
Add hard shadows and make it more dark

### ISSUE THREAD

**Issue by StarlkYT** [depressed-pho/natural-mystic-shaders#23]

**Comment by depressed-pho** [comment]
You don't like the edges of shadows being soft, right? Okay I made them a bit sharper. The problem is that the way we express shadows can't take account of distance between objects and the ground, but that's what determines the shapness of shadows as explained in this page: https://blog.demofox.org/2017/07/01/why-are-some-shadows-soft-and-other-shadows-hard/

As for darkness I took a careful balance of it and I'm not going to change it for now. In the future when the game provides a way to configure shaders in game, I will definitely make a settings screen to change various aspects of my shaders. Please bear with the status quo until then.

**Comment by depressed-pho** [comment]
A screenshot of the development version:
![4221ad1b-140a-4e4f-9ab1-ac92bb3ec626](https://user-images.githubusercontent.com/438860/50447583-84703500-095f-11e9-9125-6f714cc842fb.jpeg)
