### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by MissionApollo7** [depressed-pho/natural-mystic-shaders#25]
Everything just appears as the default resource pack on Windows 10

**Comment by StarlkYT** [comment]
Yes, me too. It doesn't work with me.

**Comment by depressed-pho** [comment]
Win10 uses a completely different shader language. In order to support it, we have to maintain two separate shader programs. That’s why most shaders don’t work on Win10. I can’t support it either, because my PCs are all Macs.

But if someone can port it and send me a pull request, I would happily merge it.

**Comment by The-Bob** [comment]
> Win10 uses a completely different shader language.

Do you know where I could find info on this?  I'm thinking of starting work on a port.

**Comment by gio1135** [comment]
> Do you know where I could find info on this? I'm thinking of starting work on a port.

You should start by learning OpenGL. Then literally any hlsl tutorial will work.

**Comment by MilkyDeveloper** [comment]
Porting won't be too hard... vec3=float3 for the most part but the hardest thing to do is remap VS/PS input for bedrock and the uniforms.
