### ISSUE TITLE
Too dark

### ISSUE THREAD

**Issue by gio1135** [depressed-pho/natural-mystic-shaders#64]
It looks absolutely great during the day, but at night and in caves and such, it's really dark. It seems as though the torch light isn't as ambient as default. I have to use twice as many torches and if I go min a section of coal or something, I need a torch in the hole with me because any nearby torches won't light it.

**Comment by depressed-pho** [comment]
That's an intentional change from vanilla. Torchlight from a single torch in vanilla can cover *very* large area, which means it emits a large amount of light energy despite it being just a small fire. The color of torchlight, which is white in vanilla, also indicates that vanilla torches behave as if they were fluorescent tubes or LEDs. This is unrealistic because the most energy they should emit is heat, not light, in reality.

However, I'm fully aware that the change is quite bad for the game play. So if you don't like the change, you can revert it back to vanilla by editing the following lines in ```shaders/glsl/natural-mystic-light.h```:

```glsl
vec3 torchLight(float torchLevel, float sunLevel, float daylight, highp float flickerFactor) {
    const float baseIntensity = 180.0;
    const float decay         = 5.0;
```

to something like:

```glsl
vec3 torchLight(float torchLevel, float sunLevel, float daylight, highp float flickerFactor) {
    const float baseIntensity = 180.0;
    const float decay         = 5.0;
```
