### ISSUE TITLE
Lighting issue

### ISSUE THREAD

**Issue by ShaderTester** [depressed-pho/natural-mystic-shaders#80]
The lighting of torches and other does not reach far. When u place down torches in vanilla the lighting reaches far but with natural mystic it does not reach as far as vanilla i would use natural mystic if the lighting did reach far but it does not pls make the lighting reach far

**Comment by gio1135** [comment]
this seems a little far fetched

**Comment by depressed-pho** [comment]
That is an intentional change. I know it isn't good for game play, but there is a reason for that.

Minecraft has a strange assumption about the energy level of torch light. It assumes that a single torch emits the same amount of energy as **the sun**, and also light decays linearly in proportion of distance. But in the real world optics, neither of those assumptions are correct. The sun is more than 1000 times brighter than just a small fire (a torch), and light decays logarithmically.
