### ISSUE TITLE
3 issues with vertex shaders and their solutions

### ISSUE THREAD

**Issue by YamaR1n** [depressed-pho/natural-mystic-shaders#85]
![Natural_Mystic_Issue](https://user-images.githubusercontent.com/81559497/116955310-25f4b780-accd-11eb-84be-4d8424217e5c.jpg)
**I noticed 3 issues with vertex shaders, and I came up with their solutions.**
### Issues

- **Plants are waving in indoor (A)**
- **Water makes weird movements when we look at them from some points (B)**
- **Chunk borders occur on plants waving (C)**

### Causes and solutions

- **A**
Strangely, plants are waving in indoors where the wind does not come in. But this issue will be solved using 'uv1.y' as a way to detect indoors.

- **B**
This issue occurs because 'gl_Position' are coordinates of the screen, not correct coordinates of the world. It will be solved to shift their codes to line-49 and rewrite 'gl_Position' to 'worldPos'.

- **C**
As we know. this issue occurs because 'POSITION' is the current chunk origin in [0.0, 16.0]. It will we solved to rewrite 'POS3 posw = POSITION.xyz;' to 'POS3 posw = abs(POSITION.xyz - 8.0);' which means to make a range of 'POSITION' from [0.0, 16.0] to [-8.0, 8.0].

**Comment by YamaR1n** [comment]
Plus: 'line-49' of B is in vanilla vertex shaders.

**Comment by gio1135** [comment]
what about when render dragon?

**Comment by depressed-pho** [comment]
>     * **A**
>       Strangely, plants are waving in indoors where the wind does not come in. But this issue will be solved using 'uv1.y' as a way to detect indoors.

That is actually a very good idea. Thank you for your suggestion.

>     * **B**
>       This issue occurs because 'gl_Position' are coordinates of the screen, not correct coordinates of the world. It will be solved to shift their codes to line-49 and rewrite 'gl_Position' to 'worldPos'.

I'm afraid I don't really understand. The line 49 of the vanilla shader is [here](https://github.com/depressed-pho/natural-mystic-shaders/blob/master/orig/shaders/glsl/renderchunk.vertex#L49), right? And is the code you thing problematic is [this](https://github.com/depressed-pho/natural-mystic-shaders/blob/master/src/shaders/glsl/renderchunk.vertex#L206)? Then I think there are no difference in these cases because both does `gl_Position = PROJ * (WORLDVIEW * worldPos);`

(P.S. If it's convenient to you, you can also use Japanese here, as I'm in fact a native Japanese speaker.)

>     * **C**
>       As we know. this issue occurs because 'POSITION' is the current chunk origin in [0.0, 16.0]. It will we solved to rewrite 'POS3 posw = POSITION.xyz;' to 'POS3 posw = abs(POSITION.xyz - 8.0);' which means to make a range of 'POSITION' from [0.0, 16.0] to [-8.0, 8.0].

Uhm I think that would only change the position where the discontinuity occurs, but I'll try your solution anyway.

**Comment by depressed-pho** [comment]
Ah I see, the `abs()` is the key to eliminate the discontinuity. Thanks, your fix did resolve the issue!

**Comment by depressed-pho** [comment]
A and C have been fixed in 38232d5bba2522f71cc866c6f312933c9b6e84a3. I did the same for the water perturbance in 46a903a642bbff750dc564392d3375681b29b239.

As for B, I still think it's because my shader perturbs not only the Y coordinate but also X and Z. Since the game doesn't tell us whether a vertex of water body is adjacent to something non-water, we have no means to accommodate the perturbance depending on the shape of the terrain. I believe it's therefore not fixable.

**Comment by YamaR1n** [comment]
日本語で書きますね。
Bについてですが、申し訳ありません。Natural Mtsticの波のコードをよく見ていませんでした。それが単に`gl_Position`に数値を足していただけなら(植物を揺らすコードと同じように)、私がBで示した解決策を使えば修正できるはずです。ESBE 2Gなどの一部のシェーダーも、それを使うことですでにこの問題を修正しています。

**Comment by YamaR1n** [comment]
はい。その問題は１で合っています。ああ、なるほど...。Gerstner Wave を使っていたのならこの問題はおそらく修正不可能ですね...。ありがとうございます。

問題２も、そもそもゲームから渡され波などの描写に使える座標が worldPos と POSITION くらいしか無いので、そちらもシェーダーに関するアップデートが来ない限り作成者はどちらか一方を選ばなければならないという状況ですよね。`floor(CHUNK_ORIGIN_AND_SCALE / 16.0) * 16.0 + POSITION.xyz` などではカメラの移動によってカクついてしまいますが、少しマシになります。試してみてください。

また、Natural Mystic に２つほどの課題を見つけたので、そちらは新しい Issue を立ててそこで指摘させていただきますね。ありがとうございました。

**Comment by depressed-pho** [comment]
試しました。確かにマシになりますね。ただチャンク境界を越える時に不連続になるのがどうしても気になるので、設定項目として追加するに留めてデフォルトでは従来通りの動作とする事にしました。ありがとうございます。
